### ISSUE TITLE
git checkout -qf failed

### ISSUE THREAD

**Issue by theambient** [Strider-CD/strider-docker-runner#30]
follow instruction `Please report at https://github.com/Strider-CD/strider/issues` )

```
git clone --recursive XYZ . -b master git 7.2s -1
Cloning into '.'...
Submodule 'XXX'
Cloning into 'XXX'...
Submodule path 'XXX': checked out 'c60603bea3f1e1384f191d6f01029c2fcd3b890c'
$ git checkout -qf master git 27ms -1
fatal: Not a git repository (or any of the parent directories): .git
$  -1
An unexpected error occurred while executing this job. Please report at https://github.com/Strider-CD/strider/issues

Checkout failed with code 128

Error: Checkout failed with code 128
    at badCode (/usr/local/lib/node_modules/strider/node_modules/strider-git/worker.js:88:11)
    at /usr/local/lib/node_modules/strider/node_modules/strider-git/worker.js:119:22
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/strider/node_modules/strider-docker-runner/node_modules/strider-runner-core/lib/job.js:203:9)
    at EventEmitter.emit (events.js:95:17)
    at /usr/local/lib/node_modules/strider/node_modules/strider-docker-runner/lib/create-container.js:108:18
    at Stream.write (/usr/local/lib/node_modules/strider/node_modules/strider-docker-runner/node_modules/event-stream/index.js:192:22)
    at Stream.stream.write (/usr/local/lib/node_modules/strider/node_modules/strider-docker-runner/node_modules/event-stream/node_modules/through/index.js:26:11)
    at Stream.ondata (stream.js:51:26)
    at Stream.EventEmitter.emit (events.js:95:17)
    at Stream.<anonymous> (/usr/local/lib/node_modules/strider/node_modules/strider-docker-runner/node_modules/event-stream/index.js:242:12)
    at Stream.stream.write (/usr/local/lib/node_modules/strider/node_modules/strider-docker-runner/node_modules/event-stream/node_modules/through/index.js:26:11)
    at Stream.ondata (stream.js:51:26)
    at Stream.EventEmitter.emit (events.js:95:17)
    at drain (/usr/local/lib/node_modules/strider/node_modules/strider-docker-runner/node_modules/event-stream/node_modules/through/index.js:36:16)
    at Stream.stream.queue.stream.push (/usr/local/lib/node_modules/strider/node_modules/strider-docker-runner/node_modules/event-stream/node_modules/through/index.js:45:5)
    at emit (/usr/local/lib/node_modules/strider/node_modules/strider-docker-runner/node_modules/event-stream/node_modules/split/index.js:36:14)
```

**Comment by theambient** [comment]
any thoughts ?

**Comment by m00t** [comment]
Same error

**Comment by knownasilya** [comment]
This is a git error. I suggest checking out the #git channel on irc.freenode.net.

```no-hgighlight
fatal: Not a git repository (or any of the parent directories): .git
```

**Comment by m00t** [comment]
I have no submodules, but have the same error. This error occures when strider tries to run git within its default strider/strider-docker-slave container. So this is definitely a strider error.

**Comment by knownasilya** [comment]
@m00t this is not the same issue as yours, since his is specifically a submodule error.

The 128 error is used for many things, unfortunately. Can you post your error message and what you did to get it.

**Comment by knownasilya** [comment]
@m00t this https://github.com/Strider-CD/strider-docker-runner/issues/17 might be your issue.

**Comment by m00t** [comment]
I started strider from my strider docker image (https://registry.hub.docker.com/u/m00t/strider/) like that:
```
    docker run --name strider-mongo-data mongo /bin/true
    
    docker run -d --name strider-mongo --volumes-from strider-mongo-data mongo
    
    docker run --rm -it \
        --link strider-mongo:mongo \
        --env="DB_URI=mongodb://mongo/strider" \
        m00t/strider \
        strider addUser
    
    docker run -d --name=strider \
        --link strider-mongo:mongo \
        --volume /run/docker.sock:/var/run/docker.sock \
        --env="DB_URI=mongodb://mongo/strider" \
        --env="PLUGIN_BITBUCKET_HOSTNAME=http://my_hostname" \
        --publish 80:3000 \
        m00t/strider
```
Then I installed docker runner plugin and configured my project to use it. Thats all. This is an error message:

```
$ git clone --recursive git@bitbucket.com:blabla/blabla . -b master bitbucket 52.8s -1
        Cloning into '.'...
        error: unable to write sha1 filename /root/.strider/data/blabla/.git/objects/pack/pack-1b69d36e06a3f7c1543701bd42968e8a73952f3f.pack: No such file or directory
        fatal: cannot store pack file
        fatal: index-pack failed
        Checking out files: 100% (6907/6907), done.
        $ git checkout -qf master bitbucket 24ms -1
        fatal: Not a git repository (or any of the parent directories): .git
        $  -1
        An unexpected error occurred while executing this job. Please report at https://github.com/Strider-CD/strider/issues
        
        Checkout failed with code 128
        
        Error: Checkout failed with code 128
            at badCode (/usr/local/lib/node_modules/strider/node_modules/strider-git/worker.js:88:11)
            at /usr/local/lib/node_modules/strider/node_modules/strider-git/worker.js:119:22
            at EventEmitter.<anonymous> (/usr/local/lib/node_modules/strider/node_modules/strider-docker-runner/node_modules/strider-runner-core/lib/job.js:203:9)
            at EventEmitter.emit (events.js:95:17)
            at /usr/local/lib/node_modules/strider/node_modules/strider-docker-runner/lib/create-container.js:108:18
            at Stream.write (/usr/local/lib/node_modules/strider/node_modules/strider-docker-runner/node_modules/event-stream/index.js:195:22)
            at Stream.stream.write (/usr/local/lib/node_modules/strider/node_modules/strider-docker-runner/node_modules/event-stream/node_modules/through/index.js:26:11)
            at Stream.ondata (stream.js:51:26)
            at Stream.EventEmitter.emit (events.js:95:17)
            at Stream.<anonymous> (/usr/local/lib/node_modules/strider/node_modules/strider-docker-runner/node_modules/event-stream/index.js:245:12)
            at Stream.stream.write (/usr/local/lib/node_modules/strider/node_modules/strider-docker-runner/node_modules/event-stream/node_modules/through/index.js:26:11)
            at Stream.ondata (stream.js:51:26)
            at Stream.EventEmitter.emit (events.js:95:17)
            at drain (/usr/local/lib/node_modules/strider/node_modules/strider-docker-runner/node_modules/event-stream/node_modules/through/index.js:36:16)
            at Stream.stream.queue.stream.push (/usr/local/lib/node_modules/strider/node_modules/strider-docker-runner/node_modules/event-stream/node_modules/through/index.js:45:5)
            at emit (/usr/local/lib/node_modules/strider/node_modules/strider-docker-runner/node_modules/event-stream/node_modules/split/index.js:36:14)
```
Seems like strider tries to clone into /root/.strider/data directory, but whoami says user is not root:
```
$ sh -x -c 'ls -la pwd whoami ls -la ~' custom 131ms
+ ls -la
total 8
drwxr-xr-x 2 strider root    4096 Dec 13 17:59 .
drwxr-xr-x 4 strider strider 4096 Dec 13 17:59 ..
+ pwd
+ whoami
/home/strider/workspace
strider
+ ls -la /home/strider
total 24
drwxr-xr-x 4 strider strider 4096 Dec 13 17:59 .
drwxr-xr-x 5 root    root    4096 Dec 13 17:59 ..
-rw-r--r-- 1 strider strider  220 Dec 13 17:59 .bash_logout
-rw-r--r-- 1 strider strider 3637 Dec 13 17:59 .bashrc
-rw-r--r-- 1 strider strider  675 Dec 13 17:59 .profile
drwxr-xr-x 2 strider root    4096 Dec 13 17:59 workspace
```

**Comment by knownasilya** [comment]
Your error has to do with permissions, since you are using root to run strider. I'm not familiar with debian directly (know ubuntu a bit), but maybe it's your node setup, like mentioned in that other issue.

```no-highlight
error: unable to write sha1 filename /root/.strider/data/blabla/.git/objects/pack/pack-1b69d36e06a3f7c1543701bd42968e8a73952f3f.pack: No such file or directory
        fatal: cannot store pack file
        fatal: index-pack failed
```

**Comment by m00t** [comment]
I suppose strider should not try to use /root/.strider/data when deploy to standard docker image.
